import {describe,it,expect} from 'vitest';
import {activeThreats,renderActiveThreats} from '../src/ui/active-threats.js';
import {incidentPins} from '../src/render/threat-markers.js';
import {workLedger} from '../src/ui/operations.js';

function fixture(){const a={id:'secret-payroll',name:'Secret payroll',discovered:true,state:'ok',x:2,y:4};const game={assets:new Map([[a.id,a]]),asset(id){return this.assets.get(id);},budget:30,price:n=>n,activeJobs:()=>0,concurrency:()=>1,humanThreatStatus:()=>[]};return{game,a};}
describe('active threat read model and actionable operations panel',()=>{
 it('never exposes the source or map position of an untraced data leak',()=>{const {game,a}=fixture();a.leak={active:true,detected:false};const rows=activeThreats(game),html=renderActiveThreats(rows,game);expect(rows).toHaveLength(1);expect(rows[0].assetId).toBeNull();expect(html).toContain('Source unknown');expect(html).not.toContain('secret-payroll');expect(html).not.toContain('Secret payroll');expect(incidentPins(game)).toEqual([]);});
 it('traces a leak only after detection and discovery',()=>{const {game,a}=fixture();a.leak={active:true,detected:true};expect(incidentPins(game)[0].assetId).toBe(a.id);a.discovered=false;expect(incidentPins(game)).toEqual([]);});
 it('keeps contained and investigating leaks open until real cleanup',()=>{const {game,a}=fixture();a.leak={active:true,detected:true};a.quarantined=true;expect(activeThreats(game)[0].state).toBe('contained');a.job={programme:'leak-clean'};expect(activeThreats(game)[0].state).toBe('investigating');a.leak.active=false;expect(activeThreats(game)).toEqual([]);});
 it('lists supply sources while quarantined but not once removed',()=>{const {game,a}=fixture();a.supplySource=true;a.state='compromised';expect(activeThreats(game)[0].state).toBe('active');a.quarantined=true;expect(activeThreats(game)[0].state).toBe('contained');a.supplySource=false;a.state='ok';expect(activeThreats(game)).toEqual([]);});
 it('does not label healthy preventive isolation as a malware incident, even with old timestamps',()=>{const {game,a}=fixture();a.state='isolated';expect(activeThreats(game)).toEqual([]);a.compromisedAt=0;expect(activeThreats(game)).toEqual([]);});
 it('shows ransomware recovery as investigating, not an unattended incident',()=>{const {game,a}=fixture();a.locked=true;a.job={kind:'ir'};expect(activeThreats(game)[0].state).toBe('investigating');});
 it('gives human investigations readable work-ledger names',()=>{const {game,a}=fixture();game.jobs=[{assetId:a.id,kind:'programme',programme:'human-human-1',remaining:22,total:25}];game.humanThreats=[{id:'human-1',kind:'worker-fraud'}];game.programReady=new Map();game.flags={};expect(workLedger(game)[0].name).toBe('Worker-fraud investigation');game.humanThreats[0].kind='insider';expect(workLedger(game)[0].name).toBe('Insider investigation');});
 it('keeps encrypted buildings active while restoring and groups colocated map pins',()=>{const {game,a}=fixture();a.locked=true;a.state='compromised';a.supplySource=true;a.job={kind:'ir'};const rows=activeThreats(game);expect(rows).toHaveLength(2);expect(rows.find(r=>r.kind==='ransom').next).toContain('Recovery in progress');expect(incidentPins(game)).toHaveLength(1);expect(incidentPins(game)[0].text).toContain('SUPPLY CHAIN + ENCRYPTED');});
 it('does not identify or locate an unconfirmed workforce signal',()=>{const {game,a}=fixture();game.humanThreatStatus=()=>[{id:'h-1',kind:'worker-fraud',state:'active',assetId:a.id,detectedAt:null}];const rows=activeThreats(game),html=renderActiveThreats(rows,game);expect(rows[0].assetId).toBeNull();expect(html).toContain('Unconfirmed workforce signal');expect(html).not.toContain('DPRK');expect(html).not.toContain('human-contain');expect(html).not.toContain('Secret payroll');expect(incidentPins(game)).toEqual([]);});
 it('allows free revocation at zero budget and full engineer capacity once detected',()=>{const {game,a}=fixture();game.budget=0;game.activeJobs=()=>1;game.humanThreatStatus=()=>[{id:'h-1',kind:'worker-fraud',state:'active',assetId:a.id,detectedAt:0}];const html=renderActiveThreats(activeThreats(game),game);expect(html).toContain('DPRK-linked');expect(html).toContain('Revoke access · free');expect(html).not.toContain('disabled');expect(incidentPins(game)[0].text).toContain('WORKER FRAUD');});
 it('shows investigation cost, time, required capacity and disabled reasons',()=>{const {game,a}=fixture();game.humanThreatStatus=()=>[{id:'h-1',kind:'insider',state:'contained',assetId:a.id,detectedAt:0,investigationCost:8,investigationSeconds:25}];const html=()=>renderActiveThreats(activeThreats(game),game);expect(html()).toContain('Verify &amp; close · $8k · ~34s');expect(html()).toContain('1 engineer');expect(html()).not.toContain('disabled');game.budget=0;expect(html()).toContain('Not enough budget');game.budget=30;game.activeJobs=()=>1;expect(html()).toContain('All engineers busy');game.activeJobs=()=>0;a.locked=true;expect(html()).toContain('Restore an available system');});
 it('removes resolved/prevented human cases rather than treating history as active',()=>{const {game,a}=fixture();game.humanThreatStatus=()=>['resolved','prevented'].map(state=>({id:state,kind:'worker-fraud',state,assetId:a.id,detectedAt:0}));expect(activeThreats(game)).toEqual([]);expect(incidentPins(game)).toEqual([]);expect(renderActiveThreats([],game)).toContain('No open incidents');});
 it('escapes names and reasons in rendered incident rows',()=>{const {game,a}=fixture();a.name='<script>x</script>';a.leak={active:true,detected:true};expect(renderActiveThreats(activeThreats(game),game)).not.toContain('<script>');});
});
