import {describe,it,expect} from 'vitest';
import {Campaign} from '../src/sim/campaign.js';
import {ORGS} from '../src/sim/orgs.js';
import {BUILTIN_DAYS,scenarioModel} from '../src/sim/scenarios.js';
import {LINES,LOSS_LINES,CAST} from '../src/audio/dialogue.js';
import {stepRealtime} from '../src/sim/realtime.js';
const mk=()=>new Campaign({model:scenarioModel(BUILTIN_DAYS[0]),org:ORGS.startup,seed:20260902});
describe('continuous leadership',()=>{
 it('retains elapsed background time and respects only explicit pause',()=>{const app={game:mk(),speed:1,running:true,paused:false,modalOpen:true,simAccumulator:0,simNow:0};stepRealtime(app,4000);expect(app.game.time).toBeCloseTo(3);stepRealtime(app,24000);for(let i=0;i<4;i++)stepRealtime(app,24000);expect(app.game.time).toBeCloseTo(18);app.paused=true;stepRealtime(app,34000);expect(app.game.time).toBeCloseTo(18);app.paused=false;stepRealtime(app,38000);expect(app.game.time).toBeCloseTo(21);});
 it('decisions do not stop preparation, building, buying or engineering',()=>{const g=mk();g.budget=10000;g.queueDilemma('ransom',null,true);g.tick(2);expect(g.time).toBe(2);expect(g.paused).toBe(false);expect(g.buy('scanner').ok).toBe(true);expect(g.place('wall',29,0).ok).toBe(true);expect(g.installEdr(g.firstAssetId).ok).toBe(true);});
 it('incoming waves advance after encryption without answering the demand',()=>{const g=mk();g.hour=12;g.phase='wave';g.phaseTimer=0;g.spawnCursor=0;g.supplyChain=[];g.detonate({assetId:g.identityId,triggered:false});expect(g.pendingDilemma.family).toBe('ransom');let arrivals=0;const spawn=g.spawn.bind(g);g.spawn=s=>{arrivals++;spawn(s);};for(let i=0;i<700;i++){g.impact=0;g.tick(.1);}expect(arrivals).toBeGreaterThan(g.waves[12].n);expect(g.hour).toBeGreaterThan(12);expect(g.pendingDilemma).not.toBeNull();});
 it('a clean company never receives the emergency sales pitch, even late in the day',()=>{const g=mk();g.hour=20;g.tickIncidents(1);expect(g.offerDetails()).toBeNull();expect(g.messages.some(m=>m.id==='salespitch_v10')).toBe(false);});
 it('one ordinary infection is insufficient, a crown compromise triggers vendor and agency',()=>{const g=mk();g.asset('mlflow').state='compromised';g.tickIncidents(1);expect(g.offerDetails()).toBeNull();g.asset('db').state='compromised';g.tickIncidents(1);expect(g.offerDetails()).toBeNull();g.time+=9;g.tickIncidents(0);expect(g.offerDetails()).not.toBeNull();expect(g.messages.some(m=>m.id==='agency_intro')).toBe(true);for(let i=0;i<500;i++){g.time++;g.tickIncidents(1);}expect(g.messages.filter(m=>m.id==='salespitch_v10')).toHaveLength(1);});
 it('another outbreak can trigger a new offer after recovery and cooldown',()=>{const g=mk();const a=g.asset('db');a.state='compromised';g.tickIncidents(1);g.time+=9;g.tickIncidents(0);g.buyVendor();a.state='ok';g.tickIncidents(1);g.time=250;a.state='compromised';g.tickIncidents(1);g.time+=9;g.tickIncidents(0);expect(g.messages.filter(m=>m.id==='salespitch_v10')).toHaveLength(2);});
 it('the pitch hides the markup but the charged price remains 150 percent',()=>{const g=mk();g.vendorOffer();const o=g.offerDetails();expect(o.price).toBe(o.regular*1.5);expect(LINES.salespitch_v10.text).not.toMatch(/percent|premium|markup|same product/i);});
 it('provides five distinct emotional board endings and a clean FBI liaison role label',()=>{expect(LOSS_LINES).toHaveLength(5);expect(new Set(LOSS_LINES.map(id=>LINES[id].text)).size).toBe(5);for(const id of LOSS_LINES)expect(LINES[id].speaker).toBe('board');expect(CAST.agency.role).toBe('FBI cyber liaison');});
 it('distinct malware avatars are mixed into device-heavy waves and bosses arrive later',()=>{const g=mk();expect(g.waves.slice(0,8).every(w=>w.attackers.every(a=>!a.boss))).toBe(true);for(const h of [11,17,23])expect(g.waves[h].attackers.some(a=>a.boss&&a.avatar==='boss')).toBe(true);expect(g.waves[4].attackers.some(a=>a.avatar==='virus')).toBe(true);const spec=g.waves[11].attackers.find(a=>a.boss);g.hour=11;g.spawn(spec);expect(g.attackers.at(-1).bossName).toBe('BLACKOUT');expect(g.messages.some(m=>m.id==='bosswarning')).toBe(true);});
});
