import {describe,it,expect} from 'vitest';
import {Campaign} from '../src/sim/campaign.js';
import {ORGS} from '../src/sim/orgs.js';
import {BUILTIN_DAYS,scenarioModel} from '../src/sim/scenarios.js';
import {radarReadout} from '../src/render/radar-labels.js';
const mk=(org='startup')=>new Campaign({model:scenarioModel(BUILTIN_DAYS[0]),org:ORGS[org],seed:42});
const fund=(g,id)=>{g.programmes.add(id);g.programReady.set(id,0);};
describe('AI campaigns, real impact feedback and governance',()=>{
 it.each(Object.keys(ORGS))('%s has exactly two AI bosses, not an endless or duplicated spawn',org=>{const g=mk(org);expect(g.waves.flatMap(w=>w.attackers).filter(a=>a.aiThreat)).toHaveLength(2);for(const h of [8,20]){g.hour=h;g.spawn(g.waves[h].attackers.find(a=>a.aiThreat));expect(g.attackers.at(-1).bossName).toBe('AI THREAT');expect(g.attackers.at(-1).aiThreat).toBe(true);}expect(g.stats.aiBosses).toBe(2);});
 it('radar exposure removes the AI damage shield without changing the web/device payload',()=>{const g=mk();g.hour=8;g.spawn(g.waves[8].attackers.find(a=>a.aiThreat));const a=g.attackers.at(-1),hp=a.hp;g.hit(a,10,g.towers[0]);expect(hp-a.hp).toBeCloseTo(6);a.intelRevealed=true;const before=a.hp;g.hit(a,10,g.towers[0]);expect(before-a.hp).toBeCloseTo(10);expect(radarReadout(a,g).category).toBe('AI THREAT');});
 it('impact labels report the actual charged hit impact',()=>{const g=mk(),a=g.asset('web'),before=g.impact;g.damage(a,20,{vuln:'test',ip:'test'},null);const e=g.effects.find(e=>e.type==='business-impact');expect(e.amount).toBeCloseTo(g.impact-before);expect(e.assetId).toBe(a.id);expect(e.amount).toBeGreaterThan(0);});
 it('ransomware allocates its actual impact across every newly encrypted building',()=>{const g=mk();g.asset(g.identityId).credTo=[...g.assets.keys()];g.effects=[];const before=g.impact;g.detonate({assetId:g.identityId});const effects=g.effects.filter(e=>e.type==='business-impact'&&e.reason==='Ransomware');expect(effects.length).toBe([...g.assets.values()].filter(a=>a.locked).length);expect(effects.reduce((n,e)=>n+e.amount,0)).toBeCloseTo(g.impact-before);});
 it('continuous loss is aggregated and throttled, not emitted on every frame',()=>{const g=mk(),a=g.asset('web');a.state='compromised';g.effects=[];for(let i=0;i<60;i++){g.time+=1/30;g.tickAssets(1/30);}expect(g.effects.filter(e=>e.type==='business-impact').length).toBeLessThanOrEqual(1);expect(a.pendingVisualImpact).toBeGreaterThan(0);});
 it('regulator evidence needs real capabilities, engineer capacity and subsequent board review',()=>{const g=mk();g.hour=4;g.tickGrc();expect(g.grc).toHaveLength(1);expect(g.startGrc('inventory').ok).toBe(false);fund(g,'scanner');for(const a of g.assets.values())a.knownVulns=new Set(a.vulns);const before=g.trust;expect(g.startGrc('inventory').ok).toBe(true);expect(g.grc[0].state).toBe('working');expect(g.activeJobs()).toBe(1);g.time+=21;g.tickJobs(21);expect(g.grc[0].state).toBe('board-review');expect(g.trust).toBe(before);g.time+=21;g.tickGrc();expect(g.grc[0].state).toBe('done');expect(g.trust).toBe(Math.min(5,before+1));expect(g.startGrc('inventory').ok).toBe(false);});
 it('a missed deadline penalizes once and late evidence cannot farm trust',()=>{const g=mk();g.hour=4;g.tickGrc();g.time=g.grc[0].deadline+1;g.tickGrc();g.tickGrc();expect(g.trust).toBe(4);expect(g.stats.grcMissed).toBe(1);fund(g,'scanner');for(const a of g.assets.values())a.knownVulns=new Set();g.startGrc('inventory');g.time+=25;g.tickJobs(25);g.time+=21;g.tickGrc();expect(g.grc[0].state).toBe('done');expect(g.trust).toBe(4);});
 it('compromising the evidence host returns the request to pending',()=>{const g=mk();g.hour=4;g.tickGrc();fund(g,'scanner');for(const a of g.assets.values())a.knownVulns=new Set();g.startGrc('inventory');const a=g.asset(g.grc[0].assetId);g.compromise(a,{vuln:'test'},null);g.tickGrc();expect(g.grc[0].state).toBe('pending');});
 it('attestation cannot be signed before both supporting requests are done',()=>{const g=mk();g.hour=18;g.tickGrc();expect(g.grc).toHaveLength(3);expect(g.startGrc('attestation').ok).toBe(false);g.grc[0].state='done';g.grc[1].state='done';expect(g.startGrc('attestation').ok).toBe(true);});
});
