import {describe,it,expect} from 'vitest';
import {Campaign} from '../src/sim/campaign.js';
import {ORGS} from '../src/sim/orgs.js';
import {BUILTIN_DAYS,scenarioModel} from '../src/sim/scenarios.js';
import {sortedAssets,workLedger,timeRemaining,navigationVisuals} from '../src/ui/operations.js';
import {LINES} from '../src/audio/dialogue.js';
import {stepRealtime} from '../src/sim/realtime.js';
const mk=(org='startup')=>new Campaign({model:scenarioModel(BUILTIN_DAYS[0]),org:ORGS[org],seed:42});
describe('v13 command-floor usability',()=>{
 it('sorts infection and encryption before healthy crown jewels without exposing shadow IT or untraced leaks',()=>{const g=mk();for(const a of g.assets.values()){a.discovered=true;a.knownVulns=new Set();}const a=g.asset('web'),b=g.asset('db');a.state='compromised';a.crit=1;expect(sortedAssets(g)[0]).toBe(a);b.locked=true;expect(sortedAssets(g)[0]).toBe(b);a.discovered=false;expect(sortedAssets(g)).not.toContain(a);b.locked=false;const before=sortedAssets(g).map(x=>x.id);a.discovered=true;a.state='ok';a.discovered=false;b.leak={active:true,detected:false};expect(sortedAssets(g).map(x=>x.id)).toEqual(before);});
 it('shows parallel rollouts, assigned work and queued recovery, then removes completed orders',()=>{const g=mk();g.budget=1000;g.buy('mfa');g.buy('backups');g.buy('drill');g.recoveryQueue=['web'];expect(workLedger(g).map(r=>r.name)).toEqual(expect.arrayContaining(['Identity provider · MFA','Tested backups','Incident drill','Recovery queued']));expect(workLedger(g).filter(r=>r.name==='Incident drill')).toHaveLength(1);g.time=121;g.tickJobs(121);expect(workLedger(g).some(r=>r.kind==='rollout')).toBe(false);});
 it('counts remaining clock hours accurately, including midnight',()=>{const g=mk();g.clock=()=> '00:00';expect(timeRemaining(g)).toBe('24h 00m left');g.clock=()=> '13:45';expect(timeRemaining(g)).toBe('10h 15m left');g.clock=()=> '24:00';expect(timeRemaining(g)).toBe('0h 00m left');});
 it('slows all simulation equally at 1x and retains real 2x/3x multipliers',()=>{for(const speed of [1,2,3]){const app={game:mk(),running:true,paused:false,speed,simNow:0,simAccumulator:0};stepRealtime(app,4000);stepRealtime(app,4000);expect(app.game.time).toBeCloseTo(3*speed);}});
 it('supports paid staged engineer upgrades with no unlimited hiring',()=>{for(const org of Object.keys(ORGS)){const g=mk(org);g.budget=1000;const base=g.concurrency();expect(g.buy('soc2').ok).toBe(false);expect(g.buy('soc1').ok).toBe(true);expect(g.concurrency()).toBe(base+1);expect(g.buy('soc2').ok).toBe(true);expect(g.concurrency()).toBe(base+2);expect(g.buy('soc2').ok).toBe(false);expect(g.concurrency()).toBeLessThanOrEqual(4);}});
 it('six engineering reactions are contextual, throttled, and do not inject infections',()=>{const g=mk();g.time=80;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_intro');g.asset('web').restricted=true;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_intro');g.time=g.flags.headNextAt+1;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_isolate');g.flags.rogueCount=1;g.time=g.flags.headNextAt+1;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_newsystem');g.zeroDays[0].landed=true;g.time=g.flags.headNextAt+1;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_patchless');g.activeJobs=()=>g.concurrency();g.time=g.flags.headNextAt+1;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_capacity');g.programReady.set('mfa',1000);g.time=g.flags.headNextAt+1;g.tickEngineering();expect(g.messages.at(-1).id).toBe('head_rollout');expect(Object.keys(g.flags.headSeen)).toHaveLength(6);expect(Object.values(LINES).filter(l=>l.speaker==='head')).toHaveLength(9);expect(g.stats.compromises).toBe(0);});
 it('logs completed rollouts once and includes waiting incident reports in the ledger',()=>{const g=mk();g.buy('training');g.time=41;g.tick(.1);g.tick(.1);expect(g.events.filter(e=>e.text==='Staff training rollout complete · protection active.')).toHaveLength(1);g.flags.pendingReport=true;expect(workLedger(g).some(j=>j.id==='queued-report')).toBe(true);});
 it('navigation uses five vector mouse diagrams with accessible descriptions',()=>{const html=navigationVisuals();expect(html.match(/<svg/g)).toHaveLength(5);expect(html).toContain('Right click: cancel selection');expect(html).toContain('Mouse wheel: zoom');});
});
