import {PROGRAM_TRACKS,TRACK_HELP,canonicalTrack,programTrack,operationTrack} from './program-taxonomy.js';
import {ICON} from './icons.js';
import {responseAction} from './response-action.js';
import '../v23.css';
import { renderOperations, operationsCounts, operationCards } from './operations-center.js';
import { renderActionDirectory } from './action-directory.js';
import { openLeaderboard } from './leaderboard.js';
import { exposureSummary, findingMetadata } from './asset-exposure.js';
import { sessionMenu } from './session-menu.js';
import { LineShuffle } from '../audio/random-lines.js';
import { utilityLabel } from './utilities.js';
import { ORGS } from '../sim/orgs.js';
import { TOWERS, ACTIONS } from '../sim/catalog.js';
import { PROGRAMS, TRACKS, CALENDAR } from '../sim/campaign-rules.js';
import { CAST, LINES, LOSS_LINES, VARIANTS } from '../audio/dialogue.js';
import {sortedAssets,workLedger,timeRemaining,navigationVisuals} from './operations.js';
import { programIcon,assetIcon,controlValue,trustVisual } from './presentation.js';
import { quickGuide } from './quick-guide.js';
import './active-threats.css';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Keep live buttons mounted while counts/timers change: replacing innerHTML on
// every update could eat a click or discard keyboard focus mid-interaction.
function patchDOM(target,html){
 const template=document.createElement('template');template.innerHTML=String(html);
 const identity=n=>n.nodeType===1?[(n.id||''),n.getAttribute('data-action')||'',n.getAttribute('data-id')||''].join('|'):'';
 const sync=(parent,fresh)=>{
  for(let i=0;i<fresh.childNodes.length;i++){
   const wanted=fresh.childNodes[i];let current=parent.childNodes[i];
   if(!current){parent.append(wanted.cloneNode(true));continue;}
   if(current.nodeName!==wanted.nodeName||identity(current)!==identity(wanted)){const match=[...parent.childNodes].slice(i+1).find(n=>n.nodeName===wanted.nodeName&&identity(n)===identity(wanted));if(match){parent.insertBefore(match,current);current=match;}else{parent.replaceChild(wanted.cloneNode(true),current);continue;}}
   if(wanted.nodeType===3){if(current.nodeValue!==wanted.nodeValue)current.nodeValue=wanted.nodeValue;continue;}
   if(wanted.nodeType!==1)continue;
   for(const attr of [...current.attributes])if(!wanted.hasAttribute(attr.name))current.removeAttribute(attr.name);
   for(const attr of [...wanted.attributes])if(current.getAttribute(attr.name)!==attr.value)current.setAttribute(attr.name,attr.value);
   sync(current,wanted);
  }
  while(parent.childNodes.length>fresh.childNodes.length)parent.lastChild.remove();
 };sync(target,template.content);
}
const money=n=>`$${Math.round(n)}<small>k</small>`;
const btn=(action,label,extra='',disabled=false)=>`<button data-action="${action}" ${extra} ${disabled?'disabled':''}>${label}</button>`;
const portrait=s=>`<div class="portrait p${CAST[s].portrait} ${s}" aria-label="${esc(CAST[s].name)}"></div>`;
export class CommandUI {
 constructor(app){this.app=app;this.root=document.querySelector('#interface');this.overlay=document.querySelector('#overlay');this.tab='build';this.track='Actions';this.signature='';this.callQueue=[];this.callUntil=0;this.lastCall=0;
 this.root.innerHTML=`<header><div class="brand-block"><span class="brand-title">CISO SIMULATOR</span><span class="brand-credit">by <a href="https://zerodayclock.com" target="_blank" rel="noopener"><i aria-hidden="true"></i>ZeroDayClock.com</a></span></div><div class="topstats"><div><label>${ICON.budget} BUDGET</label><strong id="budget"></strong><small class="metric-note">Available to spend</small></div><div><label>${ICON.chart} IMPACT</label><strong id="impact"></strong></div><div><label>${ICON.ciso} BOARD TRUST</label><button data-action="trust-help" class="trust-help" title="Starts at 5/5: full board confidence. Click to learn how to maintain it."><strong id="trust"></strong></button></div><div class="header-team"><label>${ICON.engineer} ENGINEERS</label><button data-action="work-toggle" title="Working / available capacity; open work ledger"><strong id="team-count"></strong><small id="team-status"></small></button></div><div><label>${ICON.chart} SCORE</label>${btn('score-help','Score 0','id="live-score" title="Live performance breakdown"')}<small class="metric-note">Adjusted / 10,000</small></div></div><div class="utilities">${btn('audio',utilityLabel('sound','Sound on'),'id="audio" aria-label="Sound on" title="Toggle sound"')}${btn('help',utilityLabel('help','Help'),'aria-label="How to play" title="How to play"')}${btn('menu',utilityLabel('menu','Menu'),'aria-label="Menu" title="Menu"')}</div></header>
 <section class="mission"><div class="eyebrow" id="company"></div><h1>Keep the company alive.</h1><p id="mission-advice"></p><div class="mission-progress" id="objectives"></div></section>
 <aside class="command-panel glass"><div class="tabs" role="tablist">${['build','assets','programs','team'].map(t=>btn('tab',({build:'◧ Build',assets:'▦ Assets',programs:'◉ Programs',team:'♟ Team'})[t],`data-id="${t}" role="tab"`)).join('')}</div><div id="panel"></div></aside><aside id="inspect" class="inspect glass" hidden></aside>
 <section class="work-tray glass" id="work-tray" hidden><div class="section-head"><b id="work-title">Work ledger</b>${btn('work-close','×','aria-label="Close work ledger"')}</div><div id="jobs"></div><div id="grc-body" hidden></div></section>
 <section id="risk-status" class="risk-status glass" hidden></section><div id="network-legend" class="network-legend glass" hidden></div><button id="incident-status" class="incident-status glass" data-action="ransom-help" hidden></button><section id="decision-tray" class="decision-tray glass" hidden></section><section id="boss-status" class="boss-status glass" hidden></section><section id="call" class="call glass" aria-live="polite" hidden></section><section id="activity-log" class="activity-log glass" hidden></section><button id="coach-tip" class="coach-tip glass" data-action="coach" hidden></button>${navigationVisuals()}
 <div class="view-controls glass">${btn('camera','Command','data-id="command" title="Side-on command view"')}${btn('camera','Campus','data-id="overview"')}${btn('camera','Perimeter','data-id="perimeter"')}${btn('camera','Core','data-id="core"')}${btn('labels','Labels','id="labels"')}${btn('activity','Operations','id="activity-toggle" aria-pressed="false"')}</div>
 <footer class="glass"><div class="clock"><span class="eyebrow" id="phase-label"></span><strong id="clock"></strong><span id="time-left"></span></div><div class="timeline-wrap"><div class="timeline-head"><span id="wave-label"></span><span id="data-day"></span></div><div id="timeline"></div><div class="timeline-labels"><span>00:00 / FIRST CONTACT</span><span>06:00 / BUSINESS</span><span>16:00 / SIEGE</span><span>24:00</span></div></div><div class="play-controls">${btn('early','Start wave ↗','id="early"')}${btn('pause','Ⅱ','id="pause" aria-label="Pause simulation"')}${[1,2,3].map(n=>btn('speed',`${n}×`,`data-id="${n}"`)).join('')}</div></footer>`;
 document.body.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)this.action(el.dataset.action,el.dataset.id,el);});
 this.overlay.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...this.overlay.querySelectorAll('button:not(:disabled),select,input,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault();}});
 document.body.addEventListener('change',e=>{if(e.target.id==='scenario-file')this.importDay(e.target.files[0]);});}
 action(action,id,el){const a=this.app,g=a.game;let r;
 switch(action){
 case 'work-toggle':this.workMode='team';this.workVisible=!this.workVisible;this.updateWork();return;
 case 'grc-toggle':this.openOperation('fbi-evidence');return;
 case 'operation-action':this.openOperation(id);return;
 case 'action-route':if(id==='build'||id==='assets'||id==='team'){this.tab=id;a.buildType=null;this.signature='';this.renderPanel();}else{this.activityVisible=true;this.opsView=id;this.opsHistory=false;a.select(null);this.decisionExpanded=false;this.updateExperience();}return;
 case 'ops-view':this.opsView=id;this.opsHistory=false;this.updateExperience();return;
 case 'ops-expand':this.opsExpanded??=new Set();if(this.opsExpanded.has(id))this.opsExpanded.delete(id);else this.opsExpanded.add(id);this.updateExperience();return;
 case 'ops-history':this.opsHistory=!this.opsHistory;this.updateExperience();return;
 case 'ops-decision':this.openOperation('decision');return;
 case 'evidence-defer':r=g.deferEvidence();break;
 case 'evidence-prepare':r=g.prepareEvidence();break;
 case 'evidence-share':r=g.decideEvidence(true);break;
 case 'evidence-retain':r=g.decideEvidence(false);break;
 case 'work-close':this.workVisible=false;this.updateWork();return;
 case 'grc-start':r=g.startGrc(id);break;
 case 'human-contain':r=g.containHumanThreat(id);break;
 case 'human-investigate':r=g.investigateHumanThreat(id);break;
 case 'threat-program':a.select(null);this.tab='programs';this.track=canonicalTrack(id);this.signature='';this.renderPanel();return;
 case 'start':a.start(ORGS[id]?id:'startup','full');return;
 case 'begin-duty':this.closeCall();this.closeModal();g.messages=g.messages.filter(m=>m.id!=='promotion');return;
 case 'vendor-buy':r=g.buyVendor();if(r.ok)this.closeCall();break;
 case 'vendor-regular':this.closeCall();this.track=PROGRAMS[g.flags.offer?.program]?programTrack(PROGRAMS[g.flags.offer.program]):'Recover';this.tab=this.track==='Team'?'team':'programs';this.signature='';this.renderPanel();return;
 case 'quarantine':r=g.quarantine(a.selected.id);break;
 case 'restrict':r=g.restrictService(a.selected.id);break;
 case 'leak-clean':r=g.cleanLeak(a.selected.id);break;
 case 'leak-help':this.leakHelp();return;
 case 'score-help':this.scoreHelp();return;
 case 'leaderboard':openLeaderboard(this);return;
 case 'help-page':this.help(Number(id));this.overlay.querySelector('[aria-current="page"]')?.focus();return;
 case 'trust-help':this.modal('<div class="eyebrow">BOARD CONFIDENCE</div><h2>Full confidence. Keep it.</h2><p>You start at 5/5: the board fully backs your appointment. Protect that confidence by keeping services running and commitments honest. Trust cannot exceed five.</p><p>Strong reviews, candid incident reporting and effective briefings build trust. Crown-jewel compromises, missed commitments and avoidable damage reduce it.</p>'+btn('resume','Back to work'),'help-modal');return;
 case 'coach':{const hint=g.flags.coaching;if(!hint)return;if(hint.assetId)a.select({kind:'asset',id:hint.assetId},true);else{this.tab='programs';this.track=canonicalTrack(hint.track||'Detect');this.signature='';this.renderPanel();}return;}
 case 'ransom-help':this.ransomware();return;
 case 'incident-asset':this.closeModal();a.select({kind:'asset',id},true);return;
 case 'resume':this.closeModal();return;case 'menu':this.menu();return;
 case 'restart':this.menu(true);return;
 case 'restart-confirm':a.start(g.org.id,g.mode);return;
 case 'menu-organizations':this.startScreen();return;case 'help':this.help();return;
 case 'tab':a.select(null);this.tab=id;a.buildType=null;this.signature='';this.renderPanel();return;
 case 'build':a.buildType=a.buildType===id?null:id;this.tab='build';this.signature='';this.renderPanel();return;
 case 'select':a.select({kind:'asset',id},true);return;
 case 'track':a.select(null);this.tab=id==='Team'?'team':'programs';this.track=canonicalTrack(id);this.signature='';this.renderPanel();return;
 case 'buy':r=g.buy(id);break;case 'team':a.select(null);this.tab='team';this.track='Team';this.signature='';this.renderPanel();return;
 case 'patch':case 'emergency':r=g.patch(a.selected.id,id,action==='emergency');break;
 case 'isolate':r=g.isolate(a.selected.id);break;case 'reconnect':r=g.isolate(a.selected.id,false);break;
 case 'replace':r=g.replace(a.selected.id);break;case 'edr':r=g.installEdr(a.selected.id);break;case 'respond':r=g.respond(a.selected.id,true);break;
 case 'upgrade':r=g.upgrade(a.selected.id);break;case 'sell':r=g.sell(a.selected.id);if(r.ok)a.select(null);break;
 case 'remove-wall':r=g.removeWall(a.selected.x,a.selected.y);if(r.ok)a.select(null);break;
 case 'inspect-close':a.select(null);return;case 'pause':a.paused=!a.paused;return;case 'speed':a.speed=Number(id);return;
 case 'early':r=g.startHourEarly();break;case 'audio':const enabled=a.audio.toggle();el.innerHTML=utilityLabel(enabled?'sound':'muted',enabled?'Sound on':'Sound off');el.setAttribute('aria-label',enabled?'Sound on':'Sound off');return;
 case 'labels':a.labels=!a.labels;return;case 'activity':this.activityVisible=!this.activityVisible;if(this.activityVisible){a.select(null);this.decisionExpanded=false;}this.updateExperience();return;
 case 'camera':a.rig.goTo(id);return;case 'call-close':this.closeCall();return;
 case 'decision-toggle':this.openOperation('decision');return;
 case 'choose':r=g.choose(g.pendingDilemma?.id,id);if(r.ok){document.querySelector('#decision-tray').hidden=true;}break;
 case 'file':r=g.fileIncident();break;case 'freeze':r=g.freezeChanges();break;case 'results':this.results();return;
 case 'copy':navigator.clipboard.writeText(JSON.stringify(g.shareCard(),null,2)).then(()=>this.toast('Daily summary copied.'),()=>this.toast('Clipboard unavailable. Use Download report.'));return;
 case 'download':{const url=URL.createObjectURL(new Blob([JSON.stringify({summary:g.shareCard(),scores:g.scoreBreakdown(),evidence:g.scoreEvidence(),incidentTimings:g.performance.incidents,events:g.events,decisions:g.dilemmaHistory},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`a-day-as-ciso-${g.model.day}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}}
 if(r){this.toast(r.ok?'Order confirmed.':r.reason,!r.ok);if(r.ok)a.audio.effect('build');this.signature='';this.inspectSignature='';this.update();}}
 openOperation(id){
  const row=operationCards(this.app.game,this.app.speed).find(r=>r.id===id);if(!row){this.toast('This item is resolved.');return;}
  this.activityVisible=true;this.opsHistory=false;this.decisionExpanded=false;this.closeCall();
  // A building is a target, not an extra copy of the action catalog.
  if(row.assetId&&row.kind==='threat'&&row.track!=='Protect')this.app.select({kind:'asset',id:row.assetId},true);
  else{this.app.select(null);this.tab='programs';this.track=operationTrack(row);this.signature='';this.renderPanel();requestAnimationFrame(()=>{const card=document.getElementById('program-'+id);card?.scrollIntoView({block:'nearest'});card?.querySelector('button:not(:disabled)')?.focus({preventScroll:true});});}
  this.updateExperience();
 }
 modal(html,type){this.modalType=type;this.app.modalOpen=true;this.root.inert=true;this.overlay.innerHTML=`<div class="scrim"><section class="modal ${type}" role="dialog" aria-modal="true" tabindex="-1">${html}</section></div>`;const dialog=this.overlay.querySelector('.modal');dialog?.focus({preventScroll:true});dialog.scrollTop=0;}
 closeModal(){this.modalType=null;this.app.modalOpen=false;this.root.inert=false;this.overlay.innerHTML='';}
 menu(confirm=false){if(!this.app.running){this.startScreen();return;}this.modal(sessionMenu(this.app,confirm),'session-menu');}
 startScreen(){const a=this.app,d=a.day;this.modal(`<div class="start-art" role="img" aria-label="Security controls intercept viruses, bugs and worms on the corporate campus"><div class="art-caption"><i class="live-dot"></i> THE WORLD DOESN’T STOP SCANNING.</div></div><div class="start-content"><div class="eyebrow">CYBERSECURITY TOWER DEFENSE</div><h2>CISO<br><span>SIMULATOR</span></h2><p class="game-subtitle">Keep the company alive.</p><p class="lead">The board just promoted you. Keep its trust high.<br>Pick your company. Your day starts immediately.</p><div class="organization-cards" aria-label="Choose an organization and start">${Object.values(ORGS).map((o,i)=>`<button class="organization-card" data-action="start" data-id="${o.id}"><span class="org-glyph" aria-hidden="true">${['▤','▦','▥'][i]}</span><span><b>${esc(o.name)}</b><small>${['Easy · room to learn','Medium · growing exposure','Hard · a connected estate'][i]}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div>${a.running?btn('resume','Return to your current day','class="resume-day"'):''}<div class="supported"><div class="maker"><small>Created & supported by</small><a class="zdc-wordmark" href="https://zerodayclock.com" target="_blank" rel="noopener" aria-label="ZeroDayClock"><i aria-hidden="true"></i>ZeroDayClock</a></div><a href="https://www.shadowserver.org/" target="_blank" rel="noopener"><span>24h Observation data from Shadowserver</span><img src="${import.meta.env.BASE_URL}branding/shadowserver-dark.svg" alt="The Shadowserver Foundation" /></a></div><a class="public-scoreboard-link" href="/scoreboard" target="_blank" rel="noopener">Public scoreboard ↗</a><div class="source-note"><b>${esc(d.day)} · ${d.vulnerabilities.reduce((s,v)=>s+v.connections,0).toLocaleString()} observed attempts</b><br>Daily observations shape the threat mix. Wave timing is designed for play.<details><summary>Use another day or dataset</summary><label class="file-input">Load report (.json)<input id="scenario-file" type="file" accept="application/json,.json"></label></details></div></div>`,'start-modal');}
 async importDay(file){if(!file)return;try{if(file.size>12e6)throw new Error('Use a JSON report smaller than 12 MB.');await this.app.loadDay(JSON.parse(await file.text()));this.startScreen();this.toast('Report loaded. Start a new day to use it.');}catch(e){this.toast(e.message,true);}}
 ransomware(){const g=this.app.game,s=g.ransomwareStatus();this.modal(`<div class="eyebrow">INCIDENT PLAYBOOK / OPERATIONS CONTINUE</div><h2>Ransomware, explained.</h2><div class="help-grid"><div><b>01 / Foothold</b><p>A critical system has an intruder. The 160-second timer is time left before encryption. Select that system and remove the intruder. Isolation limits spread but is not cleanup.</p></div><div><b>02 / Encryption</b><p>Linked systems lock. Their lights go out and revenue stops. Stolen credentials can cross firewalls; identity controls and EDR limit spread.</p></div><div><b>03 / Recovery</b><p>Fund tested backups under Programs → Recover. Restore each locked asset, or choose Rebuild in the ransom decision to queue all of them. Engineers and response budget are still required.</p></div><div><b>Payment ≠ recovery</b><p>Paying takes 80 seconds and still leaves your two highest-revenue systems needing a rebuild. A patch closes the hole; it does not decrypt files.</p></div></div><div class="ransom-assets">${s.dwell.map(r=>`<p>${btn('incident-asset',esc(g.asset(r.assetId)?.name),`data-id="${r.assetId}"`)} · encryption in ${Math.ceil(r.remaining)}s</p>`).join('')}${s.locked.map(b=>`<p>${btn('incident-asset',esc(b.name),`data-id="${b.id}"`)} · ${b.job?`restoring · ${Math.ceil(b.job.remaining)}s`:s.queued.includes(b.id)?'queued · waiting for capacity or budget':'locked · needs recovery'}</p>`).join('')}</div>${btn('resume','Back to the response','class="primary"')}`,'help-modal');}
 help(page=0){this.modal(quickGuide(page),'quick-guide');}
 renderPanel(){const g=this.app.game;if(!g)return;const target=document.querySelector('#panel');let html='';this.root.querySelectorAll('[data-action="tab"]').forEach(b=>{b.classList.toggle('active',b.dataset.id===this.tab);b.setAttribute('aria-selected',b.dataset.id===this.tab);});
 if(this.tab==='build'){html='<div class="panel-heading"><span>Build a control</span><small>SELECT → PLACE</small></div>';for(const t of Object.values(TOWERS))html+=`<button class="control-card ${this.app.buildType===t.id?'selected':''}" data-action="build" data-id="${t.id}" title="${esc(t.blurb+' '+controlValue(t.id))}"><img class="control-icon ${t.id}" src="${import.meta.env.BASE_URL}concepts/${t.id==='ips'?'v9':'v2'}/${t.id}.png" alt="" /><span><b>${esc(t.name)}</b><small>${controlValue(t.id)}</small></span><strong>${money(g.buildCost(t.id))}</strong></button>`;html+=`<p class="panel-note">${this.app.buildType?'Click an open tile to deploy. Green = valid. Esc cancels.':'Cover all three uplinks. No single control stops everything.'}</p>${btn('track','SIEM → Programs / Detect','data-id="Detect" class="text-link"')}`;}
 if(this.tab==='assets'){const list=sortedAssets(g);html=`<div class="panel-heading"><span>Assets · urgent first</span><small>${list.length} SYSTEMS</small></div><div class="asset-list">${list.map(a=>`<button class="asset-row ${this.app.selected?.id===a.id?'selected':''}" data-action="select" data-id="${a.id}"><img class="asset-icon" src="${assetIcon(a)}" alt="" /><i class="state-dot ${a.state}"></i><span><b>${esc(a.name)}</b><small>${a.exposed?'Internet-facing':'Internal'} · ${a.locked?'ENCRYPTED':a.state==='compromised'?'INFECTED':a.leak?.active&&a.leak.detected?'DATA LEAK':a.quarantined?'QUARANTINED':a.job?'Engineer working':a.state}</small></span><span>${a.crit===3?'◆':''}</span></button>`).join('')}</div><p class="panel-note">◆ Crown jewel · Hidden systems need discovery.</p>`;}
 if(this.tab==='programs'||this.tab==='team'){if(this.tab==='team')this.track='Team';else if(this.track==='Team')this.track='Identify';html=this.tab==='team'?`<div class="panel-heading"><span>People & response</span><small>${g.activeJobs()} / ${g.concurrency()} WORKING</small></div><p class="panel-note">${g.concurrency()-g.activeJobs()} engineers available · ${workLedger(g).length} pending orders</p><div class="work-ledger-rows">${workLedger(g).map(j=>`<p class="panel-note">${esc(j.name)} · ${j.kind==='queued'?'Queued':`${Math.ceil(j.left/(this.app.speed*.75))}s`}<br>${esc(j.detail)}</p>`).join('')}</div>`:`<div class="track-tabs">${PROGRAM_TRACKS.map(t=>btn('track',t,`data-id="${t}" class="${t===this.track?'selected':''}"`)).join('')}</div><p class="track-explanation">${TRACK_HELP[this.track]||''}</p>`;for(const p of Object.values(PROGRAMS).filter(p=>programTrack(p)===this.track)){const bought=p.id==='briefing'?g.briefed.has(g.act):g.bought(p.id),ready=g.has(p.id),left=Math.max(0,(g.programReady.get(p.id)||0)-g.time),reason=bought?'':g.programEligibility(p.id);html+=`<div class="program-card"><div><img class="program-icon" src="${programIcon(p)}" alt="" /><b title="${esc(p.name)}">${esc(p.name)}</b><strong>${bought?ready?'✓ Active':Number.isFinite(left)?`${Math.ceil(left/(this.app.speed*.75))}s`:'Assigned':money(g.programCost(p.id))}</strong></div><p>${esc(p.blurb)}</p>${btn('buy',bought?ready?'Deployed':'Rolling out':`${this.tab==='team'?'Fund team':'Fund program'}${p.seconds?` · ${Math.ceil(p.seconds/(this.app.speed*.75))}s`:''}`,`data-id="${p.id}"`,bought||!!reason)}${reason?`<small>${esc(reason)}</small>`:''}</div>`;}if(this.tab==='programs')html+=renderActionDirectory(g,this.app.speed,this.track);}
 if(html!==this.signature){const scroll=target.scrollTop;patchDOM(target,html);target.scrollTop=scroll;this.signature=html;}}
 renderInspect(){const a=this.app,g=a.game,s=a.selected,el=document.querySelector('#inspect');if(!s){el.hidden=true;return;}el.dataset.kind=s.kind;let html=btn('inspect-close','×','class="close" aria-label="Close inspector"');
 if(s.kind==='asset'){const b=g.asset(s.id);if(!b)return;html+=`<img class="inspect-asset-icon" src="${assetIcon(b)}" alt="" /><div class="eyebrow">${b.exposed?'PERIMETER / INTERNET-FACING':'INTERNAL / BUSINESS SYSTEM'}${b.crit===3?' / CROWN JEWEL':''}</div><h2>${esc(b.discovered?b.name:'Unlisted system')}</h2><p>${esc(b.discovered?b.product:'Discover this system to manage it.')}</p>`;if(b.discovered){html+=`<div class="asset-metrics"><span><label>STATE</label><b class="${b.state}">${b.locked?'ENCRYPTED':b.state.toUpperCase()}</b></span><span><label>INTEGRITY</label><b>${Math.round(b.integrity)}%</b></span><span><label>ENDPOINT</label><b>${b.edr?'GUARDED':b.canEdr&&!b.appliance?'NO AGENT':'APPLIANCE'}</b></span></div>`;if(b.quarantined)html+='<p class="warning">NETWORK QUARANTINE · spread and data loss stopped. Restore service by removing the intruder or leak collector.</p>';if(b.supplySource)html+=`<p class="warning">POISONED UPDATE · spawns ${Math.max(1,Math.ceil(g.waves[g.hour]?.n*.1||1))} malware sources per wave from this building until cleaned. Quarantine stops new emissions.</p>`;if(b.leak?.detected&&b.leak.active)html+=`<div class="ransom-explainer"><b>DATA LEAK · ${b.leak.amount.toFixed(1)} GB LOST</b><p>Quarantine stops outbound transfer. Remove the collector and rotate credentials to recover safely.</p>${btn('quarantine','Quarantine egress','',b.quarantined)}${btn('leak-clean','Remove collector · 25s','',!!b.job)}</div>`;if(b.locked)html+=`<p class="warning">Files encrypted · revenue stopped. ${g.has('backups')?'Restore from tested backups. An engineer stays assigned until recovery completes.':'Fund Programs → Recover → Tested backups, then restore.'}</p>`;if(b.job)html+=`<div class="job-current"><b>${esc(b.job.kind==='ir'?'Incident response':b.job.kind)} in progress</b><span>${Math.ceil(b.job.remaining)}s</span><progress value="${b.job.total-b.job.remaining}" max="${b.job.total}"></progress></div>`;
 html+=`<div class="asset-actions">${['compromised','responding'].includes(b.state)?responseAction(g,b,a.speed):b.state==='isolated'?btn('reconnect','Reconnect (risk returns)'):btn('isolate',`Unplug · ${money(({startup:5,midcap:8,enterprise:12}[g.org.id])*2**g.act)}`,'',!!b.job)}${!b.edr&&b.canEdr&&!b.appliance?btn('edr',`Deploy EDR · ${money(g.price(8+4*b.crit))}`,'',!!b.job):''}`;
 if(b.state==='compromised'&&!b.quarantined)html+=btn('quarantine',`Emergency quarantine · ${money(g.price(5))}`);if(b.exposed)html+=btn('restrict',b.restricted?'Re-enable public service':'Disable public service · keep 70% revenue','title="Stops public network attempts while preserving private operations. Not a patch; restore only after fixing."');
 html+='</div>';const vulns=b.knownVulns;html+=`<h3>SCANNER FINDINGS</h3>${exposureSummary(g,b)}${!vulns?.size?'':[...vulns].map(id=>{const v=g.vuln(id),fix=g.fixHour(id);return`<div class="vuln"><b>${esc(id)}</b>${findingMetadata(g,id)}<p>${!v?.patchable?'NO PATCH AVAILABLE. Disable the public service, quarantine, or replace. EDR and matching IPS/WAF rules reduce risk; they do not remove the vulnerability.':fix!==null?`NO PATCH YET · expected ${String(fix).padStart(2,'0')}:00. Disable the public service or unplug; layer EDR and matching IPS/WAF coverage.`:'Vendor fix available'}${b.queuedFix?.vid===id?' · QUEUED':''}</p>${v?.patchable?btn('patch',fix!==null?'Check / queue fix':`Patch · ${money(g.price(ACTIONS.patchCost(b)))}`,`data-id="${esc(id)}"`,!!b.job):btn('replace',`Replace · ${money(g.price(ACTIONS.replaceCost(b)))}`,'',!!b.job)}${v?.patchable&&fix===null?btn('emergency','Emergency change',`data-id="${esc(id)}" title="Faster, 50% more expensive; can fail"`,!!b.job):''}</div>`;}).join('')}`;html+=g.countdowns().filter(t=>t.visible&&t.assetId===b.id).map(t=>`<p class="warning">${t.kind==='ransomware'?'Encryption dwell':'Business reconnect'} · ${Math.ceil(t.remaining)}s</p>`).join('');}}
 else if(s.kind==='tower'){const t=g.towers.find(t=>t.id===s.id);if(!t){a.select(null);return;}const d=TOWERS[t.type],up=d.levels[t.level].upgrade;html+=`<div class="eyebrow">NETWORK CONTROL / LEVEL ${t.level+1}</div><h2>${d.name}</h2><p>${esc(d.blurb)}</p><p class="control-value">${esc(controlValue(t.type,t.level))}</p><p class="muted">Control integrity ${Math.ceil(t.hp??120)} / ${t.maxHp??120}. Attackers breach this control when all open routes are blocked.</p><div class="asset-metrics"><span><label>RANGE</label><b>${g.towerRange(t)}</b></span><span><label>IN RANGE</label><b>${t.readout?.inRange||0}</b></span><span><label>THROUGHPUT</label><b>${Math.round((t.readout?.pct||1)*100)}%</b></span></div>${up?btn('upgrade',`Upgrade · ${money(g.price(up))}`,'class="primary"'):''}${btn('sell','Sell control')}`;a.campus.showRange(t.x,t.y,g.towerRange(t));}
 else if(s.kind==='wall'){const wall=g.walls.get(s.y*30+s.x);if(!wall){a.select(null);return;}html+=`<p class="muted">Barrier integrity ${Math.ceil(wall.hp??180)} / ${wall.maxHp??180}</p>`;html+='<div class="eyebrow">SEGMENTATION</div><h2>Firewall segment</h2><p>Redirects network paths, not stolen logins. If every route is sealed, attackers damage and destroy the blocking control.</p>'+btn('remove-wall',`Remove segment · +${money(g.wallRefund(wall))}`);}
 else if(s.kind==='attacker'){const at=g.attackers.find(x=>x.id===s.id);if(!at){a.select(null);return;}html+=`<div class="eyebrow">${at.boss?'CAMPAIGN BOSS':at.kind==='lateral'?'LATERAL MOVEMENT':at.avatar==='virus'?'MALWARE PAYLOAD':'REPRESENTATIVE SOURCE'}</div><h2>${at.boss?esc(at.bossName||'BLACKOUT'):at.intelRevealed?esc(at.vuln):'Unidentified source'}</h2><p>${!at.intelRevealed?'Move a threat intel radar into range to identify exploit, category and target.':at.malware?'SUPPLY-CHAIN MALWARE · a self-propagating worm inside the estate.':at.credential?'STOLEN CREDENTIALS · bypasses network segmentation.':at.web?'WEB EXPLOIT · WAF slows and burns it; IPS is inefficient.':'DEVICE EXPLOIT · IPS bursts are effective; WAF has no effect.'}</p><p>${at.breaching?'Breaching a blocked route. The control takes damage until it breaks.':at.withdrawing?'No reachable target. Withdrawing from the estate.':at.turnedAway?'Probe only: no exploitable target. This attempt cannot compromise the service.':at.intelRevealed?`Target: ${esc(g.asset(at.targetId)?.discovered?g.asset(at.targetId).name:'unlisted system')} · ${at.malware?'internal source':esc(g.vuln(at.vuln)?.product||'credential movement')} · ${Math.ceil(at.hp)} / ${Math.ceil(at.maxHp)} strength`:'Target unknown · radar required'}</p>`;}
 el.hidden=false;if(html!==this.inspectSignature){const scroll=el.scrollTop;patchDOM(el,html);el.scrollTop=scroll;this.inspectSignature=html;}}
 enqueue(id){if(!LINES[id]||this.callQueue.includes(id))return;if(['ransom','ransomware_help','compromise','crownpanic','leakfound','lost',...LOSS_LINES].includes(id)){this.closeCall();this.callQueue.unshift(id);}else if(id==='salespitch_v10')this.callQueue.unshift(id);else this.callQueue.push(id);if(this.callQueue.length>5)this.callQueue.splice(1,this.callQueue.length-5);}
 closeCall(){this.currentCall=null;this.callUntil=0;document.querySelector('#call').hidden=true;this.app.audio.currentVoice?.pause();if(this.app.audio.music)this.app.audio.music.volume=this.app.audio.musicVolume;}
 nextLine(id){this.lineShuffle??=new LineShuffle();return this.lineShuffle.pick(id,VARIANTS[id]||[id]);}
 showCall(eventId){this.currentCall=eventId;const id=this.nextLine(eventId);const l=LINES[id],c=CAST[l.speaker],el=document.querySelector('#call'),clip=this.app.audio.videoManifest?.[l.speaker]?.file;this.callUntil=performance.now()+30000;this.lastCall=performance.now();el.hidden=false;el.innerHTML=`${clip&&/^media\/[a-z]+\.mp4$/.test(clip)?`<video class="portrait" src="${import.meta.env.BASE_URL}${clip}" autoplay muted loop playsinline aria-label="${esc(c.name)} incoming call"></video>`:portrait(l.speaker)}<div class="call-text"><div class="eyebrow"><i class="live-dot"></i> ${esc(c.role)} / INCOMING</div><h3>${esc(c.name)}</h3><p>“${esc(l.text.replace(/\[[^\]]+\]/g,''))}”</p><div class="voice-wave" aria-hidden="true">${Array.from({length:22},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>${eventId==='salespitch_v10'?this.offerMarkup():''}${l.speaker==='agency'&&this.app.game.evidence?`<div class="vendor-offer"><b>Optional evidence request</b><p>Preserve logs before choosing whether to share. This does not stop malware.</p>${btn('grc-toggle','Review evidence request')}</div>`:''}</div>${btn('call-close','×','class="close" aria-label="Dismiss call"')}`;this.app.audio.say(id,()=>{this.callUntil=performance.now()+1800;el.classList.add('finished');});el.classList.remove('finished');if(eventId==='promotion')el.querySelector('.portrait')?.classList.add('promotion');}
 decision(d){const el=document.querySelector('#decision-tray');if(!d){el.hidden=true;return;}if(this.decisionId!==d.id){this.decisionId=d.id;this.decisionExpanded=false;this.closeCall();}this.app.game.describeDilemma(d);el.hidden=false;el.classList.toggle('expanded',this.decisionExpanded);patchDOM(el,`<button class="decision-heading" data-action="decision-toggle" aria-expanded="${this.decisionExpanded}"><span><small>LIVE DECISION · OPERATIONS CONTINUE</small><b>${esc(d.title)}</b></span><span>${this.decisionExpanded?'−':'+'}</span></button>${this.decisionExpanded?`<p>${esc(d.cause)}</p><div class="choices">${d.choices.map(c=>`<button data-action="choose" data-id="${c.id}" ${!c.enabled?'disabled':''}><b>${esc(c.label)} ↗</b><p>${esc(c.consequence)}</p>${!c.enabled?`<small>${esc(c.requires)}</small>`:''}</button>`).join('')}</div><small>You can keep building and assigning engineers. Minimize this card if needed.</small>`:''}`);}
 results(){const g=this.app.game;if(['won','lost'].includes(g.phase))this.ended=true;let loss='';if(g.phase==='lost'){if(!g.flags.lossLine){this.lineShuffle??=new LineShuffle();g.flags.lossLine=this.lineShuffle.pick('loss-event',LOSS_LINES);}loss=g.flags.lossLine;this.closeCall();this.callQueue=[];g.flags.lossClip??=this.nextLine(loss);this.app.audio.say(g.flags.lossClip);}this.modal(`<div class="eyebrow">${esc(g.org.name)} / ${esc(g.model.day)} / DIFFICULTY-ADJUSTED DAILY REPORT</div><h2>${g.phase==='lost'?'Runway exhausted.':g.mode==='shift'?'First shift complete.':'You made it to midnight.'}</h2><p class="lead">${g.rank()} <span class="score-total">${g.score().toLocaleString()} / 10,000</span></p>${loss?`<div class="loss-statement">${portrait('board')}<div><div class="eyebrow">RICHARD VOSS / BOARD CHAIR</div><blockquote>“${esc(LINES[g.flags.lossClip].text.replace(/\[[^\]]+\]/g,''))}”</blockquote><small>Board debrief</small></div></div>`:''}<div class="scores">${g.scoreBreakdown().map(c=>`<div><span>${c.name}</span><strong>${c.value.toLocaleString()}<small> / ${c.max.toLocaleString()}</small></strong><progress value="${c.value}" max="${c.max}"></progress><p>${esc(c.detail)}</p></div>`).join('')}</div><div class="debrief"><h3>TOMORROW’S PRIORITIES</h3><p>${g.stats.compromises?'Contain earlier. Every compromised system creates another route inside.':'No compromised systems. Keep that prevention discipline.'} ${g.fatigue.active?'Your engineers finished fatigued. Fund capacity before the siege.':''} ${g.flags.paid?'The ransom bought time, not complete recovery.':''}</p></div><div class="result-actions">${btn('leaderboard','Compare & submit score ↗','class="primary"')}${btn('menu-organizations','Choose an organization','class="primary"')}${btn('download','Download report')}${btn('copy','Copy summary')}${btn('resume','Inspect campus')}</div><p class="muted">Public rankings are opt-in and server-verified. Daily observed counts inform a designed simulation, not a prediction of your organization’s risk.</p>`,'result-modal');}
 update(){const a=this.app,g=a.game;if(!g)return;const set=(id,value)=>{const el=document.getElementById(id);if(el.innerHTML!==String(value))patchDOM(el,value);};set('budget',money(g.budget));set('impact',`${g.impact.toFixed(1)}<small> / 100</small><progress aria-label="Business impact" value="${g.impact}" max="100"></progress>`);set('trust',trustVisual(g.trust));set('company',`${esc(g.org.name)} / ${g.mode==='shift'?'FIRST SHIFT':'FULL DAY'}`);set('clock',g.clock());set('time-left',timeRemaining(g));set('phase-label',a.paused?'MANUALLY PAUSED':g.phase==='prep'?'PREPARE NEXT HOUR':['won','lost'].includes(g.phase)?'DAY COMPLETE':'LIVE OPERATIONS');if(this.lastTrust!=null&&this.lastTrust!==g.trust&&a.running)a.audio.effect(g.trust<this.lastTrust?'breach':'build');this.lastTrust=g.trust;document.querySelector('#audio').setAttribute('aria-pressed',a.audio.enabled);const obj=g.objectives().find(o=>!o.done&&(g.bought('scanner')||o.id==='scan'));set('mission-advice',g.hour===0&&g.time<20&&![...g.assets.values()].some(a=>a.locked||a.state==='compromised')?'No active infection. Buy a Scanner, then cover the uplinks.':g.hour<6?esc(obj?.text||'Hold the perimeter until morning.'):esc(g.advisor.at(-1)?.text||'Protect operations. Keep an engineer available.'));set('objectives',g.hour<6?g.objectives().map(o=>`<i class="${o.done?'done':''}" title="${esc(o.text)}"></i>`).join(''):'');
 set('live-score',`${g.score().toLocaleString()}`);document.querySelector('.trust-help').classList.toggle('earned',g.hour>0||g.trust!==5);this.updateWork();this.updateExperience();this.updateRisks();const incident=g.ransomwareStatus(),incidentEl=document.querySelector('#incident-status');incidentEl.hidden=incident.stage==='clear';incidentEl.innerHTML=incident.stage==='encrypted'?`<b>RANSOMWARE / ${incident.locked.length} SYSTEMS ENCRYPTED</b><span>${incident.restoring.length} restoring · ${incident.queued.length} queued · What do I do? ↗</span>`:`<b>RANSOMWARE FOOTHOLD / ${Math.ceil(Math.min(...incident.dwell.map(r=>r.remaining)))}s TO ENCRYPTION</b><span>Remove the intruder before the timer expires ↗</span>`;set('team-count',`${g.activeJobs()} / ${g.concurrency()}`);set('team-status',`${Math.max(0,g.concurrency()-g.activeJobs())} free · ${workLedger(g).length} orders${g.fatigue.active?' · tired':''}`);const ledger=workLedger(g),hire=['soc1','soc2'].find(id=>!g.bought(id));set('jobs',`<div class="work-ledger-head"><span>WORK IN PROGRESS</span><span>${ledger.length} orders</span></div><div class="work-ledger-rows">${ledger.map(j=>`<${j.assetId?'button':'div'} class="job-row ${j.kind}" ${j.assetId?`data-action="select" data-id="${esc(j.assetId)}"`:''}><span>${esc(j.name)} <b>${j.kind==='queued'?'Queued':`${Math.ceil(j.left/(a.speed*.75))}s`}</b></span><small>${esc(j.detail)}</small>${j.total?`<progress aria-label="${esc(j.name)} progress" value="${j.total-j.left}" max="${j.total}"></progress>`:''}</${j.assetId?'button':'div'}>`).join('')||'<p class="team-idle">No pending work. Engineers ready.</p>'}</div>${hire?btn('buy',`+ Hire engineer · ${money(g.programCost(hire))}`,`data-id="${hire}" class="team-hire"`,g.budget<g.programCost(hire)||!!PROGRAMS[hire].requires&&!g.has(PROGRAMS[hire].requires)):'<p class="team-idle">Full team · all shifts funded</p>'}`);
 set('wave-label',`${String(Math.min(24,g.hour)).padStart(2,'0')}:00 / ${esc(CALENDAR[g.hour]?.[2]||'Handover complete')} ${g.phase==='prep'?`· ${Math.ceil(g.phaseTimer)}s preparation`:''}`);set('data-day',`${esc(g.model.day)} / ${a.fps||'—'} FPS`);set('timeline',Array.from({length:24},(_,i)=>`<i class="${i===g.hour?'current':i<g.hour?'elapsed':''} ${g.strip[i]==='✖'?'breached':''} ${[5,11,17,23].includes(i)?'surge':''}" title="${String(i).padStart(2,'0')}:00 · ${esc(CALENDAR[i][2])}"></i>`).join(''));
 const terminal=['won','lost'].includes(g.phase),early=document.querySelector('#early');early.disabled=!terminal&&g.phase!=='prep';early.dataset.action=terminal?'results':'early';early.textContent=terminal?'Daily report ↗':'Start wave ↗';document.querySelector('#pause').textContent=a.paused?'▶':'Ⅱ';document.querySelector('#labels').classList.toggle('active',a.labels);this.root.querySelectorAll('[data-action="speed"]').forEach(b=>b.classList.toggle('active',Number(b.dataset.id)===a.speed));this.renderPanel();this.renderInspect();const now=performance.now();if(this.currentCall==='salespitch_v10'&&!g.offerDetails())this.closeCall();if(this.callUntil&&now>this.callUntil)this.closeCall();if(!this.callUntil&&this.callQueue.length&&now-this.lastCall>4500&&!a.modalOpen&&!(innerWidth<=900&&g.pendingDilemma&&this.decisionExpanded)){const id=this.callQueue.shift();if((id!=='succession'||g.trust<=1)&&(id!=='salespitch_v10'||g.offerDetails())&&(!id.startsWith('hint_')||g.flags.coachIds?.includes(id)))this.showCall(id);}this.decision(['won','lost'].includes(g.phase)?null:g.pendingDilemma);this.updateBoss();if(['won','lost'].includes(g.phase)&&!this.ended){this.ended=true;this.results();}}

 promotion(){this.app.game.messages=this.app.game.messages.filter(m=>m.id!=='promotion');this.callQueue=this.callQueue.filter(id=>id!=='promotion');this.showCall('promotion');}
 updateWork(){document.querySelector('#work-tray').hidden=!this.workVisible;document.querySelector('#jobs').hidden=false;document.querySelector('#grc-body').hidden=true;document.querySelector('#work-title').textContent='Work ledger';}
 updateBoss(){const g=this.app.game,b=g.attackers.find(a=>a.alive&&a.boss),el=document.querySelector('#boss-status');el.hidden=!b;if(b)patchDOM(el,`<span class="eyebrow">CAMPAIGN BOSS / ${b.web?'WEB PAYLOAD':'DEVICE PAYLOAD'}</span><b>${esc(b.bossName||'BLACKOUT')} <small>${Math.ceil(b.hp)} / ${Math.ceil(b.maxHp)}</small></b><progress value="${Math.max(0,b.hp)}" max="${b.maxHp}"></progress><span>Armored · ${b.aiThreat?'Adaptive shield: radar reveals, then match WAF / IPS':b.web?'WAF slows; upgraded IPS supports':'upgrade IPS; WAF cannot stop device exploits'}</span>`);}
 offerMarkup(){const o=this.app.game.offerDetails();return o?`<div class="vendor-offer"><b>${esc(o.name)} · $${Number.isInteger(o.price)?o.price:o.price.toFixed(1)}<small>k</small></b><p>Emergency order · ${PROGRAMS[o.program].seconds}s deployment</p>${btn('operation-action','Review offer ↗','data-id="vendor-offer"')}${btn('call-close','Not now')}</div>`:'<p class="muted">This offer is no longer available.</p>';}
 leakHelp(){const g=this.app.game,s=g.leakStatus();this.modal(`<div class="eyebrow">DATA LOSS / OPERATIONS CONTINUE</div><h2>Data is leaving the company.</h2><p>Unusual outbound volume does not identify the source. Fund <b>Programs → Detect → Data loss monitoring</b>. Radar and SIEM do not replace it.</p><p>Once traced, upward data packets mark the building. <b>Quarantine egress</b> immediately, then assign an engineer to <b>remove the collector and rotate credentials</b>. Detection alone does not stop data loss.</p>${s.detected.map(a=>btn('incident-asset',esc(a.name),`data-id="${a.id}"`)).join('')}${btn('resume','Back to the campus','class="primary"')}`,'help-modal');}
 updateRisks(){const g=this.app.game,el=document.querySelector('#risk-status'),crowns=[...g.assets.values()].filter(a=>a.crit===3&&(a.locked||a.quarantined||['compromised','down','responding'].includes(a.state))),leak=g.leakStatus();el.hidden=!crowns.length&&!leak.active;patchDOM(el,`${crowns.length?`<button class="crown-alert" data-action="select" data-id="${crowns[0].id}"><b>◆ ${crowns.length} CROWN JEWEL${crowns.length===1?'':'S'} DOWN</b><span>Critical business service interrupted ↗</span></button>`:''}${leak.active?`<button data-action="leak-help"><b>↟ DATA LOSS / ${leak.detected.length?'SOURCE TRACED':'SOURCE UNKNOWN'}</b><span>${leak.detected.length?'Quarantine egress, then remove collector':'Data loss monitoring required'} ↗</span></button>`:''}`);const legend=document.querySelector('#network-legend'),items=[g.has('mfa')?'◈ Amber wires · Identity provider':'',g.has('awareness')?'◈ Teal wires · SIEM':'',g.has('backups')?'◈ Backup links verified':'',g.has('dlp')?'↟ Data loss tracing active':''].filter(Boolean);legend.hidden=!items.length;patchDOM(legend,items.join('<br>'));if(this.currentCall==='salespitch_v10'){const offer=document.querySelector('.vendor-offer');if(offer&&!g.offerDetails())patchDOM(offer,'<p>Offer expired or already funded.</p>');}}

 scoreHelp(){const g=this.app.game;this.modal(`<div class="eyebrow">LIVE PERFORMANCE / OPERATIONS CONTINUE</div><h2>Outcomes, not shopping.</h2><p class="lead">${g.score().toLocaleString()} / 10,000 · snapshot at ${g.clock()}</p><div class="scores">${g.scoreBreakdown().map(c=>`<div><span>${c.name}</span><strong>${c.value.toLocaleString()}<small> / ${c.max.toLocaleString()}</small></strong><progress value="${c.value}" max="${c.max}"></progress><p>${esc(c.detail)}</p></div>`).join('')}</div><div class="score-rules"><p><b>Business resilience:</b> low damage, critical-service uptime and less data lost.</p><p><b>Defense effectiveness:</b> stop relevant threats, close or contain real exposure, and do it with less net spend. Unrelated internet noise and buying extra equipment earn no points.</p><p><b>Response & leadership:</b> detect, contain and recover quickly. Unresolved incidents earn no recovery credit. Early prevention, timely reporting, board confidence and a rested team also count.</p><p><b>All difficulties, one leaderboard.</b> Outcome quality is adjusted for challenge: Easy q, Medium q⁰·⁸⁵, Hard q⁰·⁷⁵. Day completion is applied afterward; harder starts do not earn free points. All three levels share a 10,000-point ceiling.</p><p>Scores grow with the portion of the day completed. The same day and exactly the same decisions produce the same score. A changing total reflects performance, not random bonuses. Final scores lock when the day ends. Active capabilities count through their results; mere purchase and rollout do not.</p></div>${btn('resume','Back to the command floor','class="primary"')}`,'score-help');}
 updateExperience(){const g=this.app.game,el=document.querySelector('#activity-log'),counts=operationsCounts(g),toggle=document.querySelector('#activity-toggle');el.hidden=!this.activityVisible;toggle.setAttribute('aria-pressed',!!this.activityVisible);toggle.classList.toggle('has-threats',!!counts.threats);toggle.setAttribute('aria-label',`Operations · ${counts.threats} threats · ${counts.governance} requests`);patchDOM(toggle,`Operations${counts.threats+counts.governance?` <span class="open-threat-count">${counts.threats+counts.governance}</span>`:''}`);if(this.activityVisible)patchDOM(el,renderOperations(g,this.app.speed,this.opsHistory,this.opsView||'all',this.opsExpanded||new Set()));const tip=document.querySelector('#coach-tip'),hint=g.flags.coaching;tip.hidden=!hint;tip.innerHTML=hint?`<span class="eyebrow">MAYA / NEXT STEP</span><b>${esc(hint.text)}</b><small>${hint.assetId?'Open affected asset':'Open Detect programs'} ↗</small>`:'';}
 toast(text,error=false){const el=document.querySelector('#toast');el.textContent=text;el.classList.toggle('error',error);el.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
}
