import {RULESET,SCENARIO} from '../scoreboard-config.js';
import '../leaderboard.css';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});let data;try{data=await r.json();}catch{throw Error('Leaderboard unavailable. Your game is still playable.');}if(!r.ok)throw Error(data.error||'Leaderboard unavailable.');return data;}
export const beginRankedRun=org=>import.meta.env.DEV&&import.meta.env.VITE_GAME_RANKED!=='1'?Promise.resolve({error:'Local practice run. Play the hosted game to enter the public rankings.'}):api('/api/run',{org,ruleset:RULESET,scenario:SCENARIO}).catch(error=>({error:error.message}));
export function openLeaderboard(ui){
 ui.modal('<div id="leaderboard"></div><button data-action="resume" class="leaderboard-back">Back to game</button>','leaderboard-modal');
 mountLeaderboard(ui.overlay.querySelector('#leaderboard'),{game:ui.app.game,run:ui.app.journal,ticket:ui.app.runTicket});
}
export function mountLeaderboard(root,{game,run,ticket}={}){
 const ended=game&&['won','lost'].includes(game.phase),eligible=ended&&run?.eligible;
 let org=game?.org.id||'startup',view='top',page=0,serial=0;
 root.innerHTML=`<div class="eyebrow">THE BOARD IS WATCHING</div><h2>THE CISO<br><span>HALL OF SURVIVORS.</span></h2><p class="lb-intro">Real runs. Real scores. Questionable coping mechanisms.</p>${eligible?`<form class="lb-submit"><div><b>YOUR DAY · ${game.score().toLocaleString()} POINTS</b><small>Publish your callsign and signature superskill.</small></div><label>Callsign<input name="name" minlength="2" maxlength="28" placeholder="The Patch Whisperer" required autocomplete="off"></label><label>Superskill<input name="superskill" minlength="2" maxlength="40" placeholder="Explaining DNS to the board" required autocomplete="off"></label><label class="lb-consent"><input name="consent" type="checkbox" required>Publish this score, callsign and superskill publicly. Use a nickname, not personal information.</label><button type="submit">Submit my score ↗</button><p class="lb-status" role="status"></p></form>`:ended?'<p class="lb-note">Practice run: imported scenarios, offline starts and modified simulations do not enter the public rankings.</p>':''}<div class="lb-filters"><label>Organization<select class="lb-org"><option value="startup">Easy · Startup</option><option value="midcap">Standard · Midcap</option><option value="enterprise">Expert · Enterprise</option></select></label><div class="lb-switch"><button data-view="top" aria-pressed="true">Top scores</button><button data-view="history" aria-pressed="false">Run history</button></div></div><p class="lb-scenario">Scenario ${SCENARIO} · current rules · server-verified simulation</p><div class="lb-rows" aria-live="polite"></div><div class="lb-pagination"><button class="lb-prev">← Previous</button><span></span><button class="lb-next">Next →</button></div><p class="lb-note">Ranks compare the same difficulty, scenario and rules. Callsigns are not verified identities. Automated play is not ruled out. <a href="/scoreboard" target="_blank" rel="noopener">Open public scoreboard ↗</a></p>`;
 root.querySelector('.lb-org').value=org;
 const load=async()=>{const request=++serial,rows=root.querySelector('.lb-rows');rows.innerHTML='<p class="lb-empty">Checking the boardroom…</p>';root.querySelector('.lb-prev').disabled=true;root.querySelector('.lb-next').disabled=true;
  try{const data=await api('/api/scores?'+new URLSearchParams({org,view,page}));if(request!==serial||!root.isConnected)return;rows.innerHTML=data.rows.length?data.rows.map((r,i)=>`<article class="lb-row"><span class="lb-rank">${view==='top'?String(page*25+i+1).padStart(2,'0'):'↗'}</span><div><b>${esc(r.name)}</b><p>${esc(r.superskill)}</p><small>${esc(new Date(r.created_at).toLocaleDateString())} · ${r.outcome==='won'?'Survived midnight':'Board debrief'}</small></div><strong>${Number(r.score).toLocaleString()}<small> / 10,000</small></strong></article>`).join(''):'<p class="lb-empty">No scores yet. The first seat is yours.</p>';root.querySelector('.lb-prev').disabled=page===0;root.querySelector('.lb-next').disabled=!data.more;root.querySelector('.lb-pagination span').textContent='Page '+(page+1);}
  catch(e){if(request===serial&&root.isConnected)rows.innerHTML=`<p class="lb-empty">${esc(e.message)}<br><button class="lb-retry">Try again</button></p>`;}
 };
 root.querySelector('.lb-org').addEventListener('change',e=>{org=e.target.value;page=0;load();});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view){view=b.dataset.view;page=0;root.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));load();}else if(b.classList.contains('lb-prev')){page--;load();}else if(b.classList.contains('lb-next')){page++;load();}else if(b.classList.contains('lb-retry'))load();});
 root.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,status=form.querySelector('.lb-status'),button=form.querySelector('button');if(!form.reportValidity()||!form.elements.consent.checked)return;button.disabled=true;status.textContent='Replaying your decisions and verifying the score…';
  try{const session=await ticket;if(!session?.token)throw Error(session?.error||'This run started offline. Start a new game online to rank.');if(run.submitted)throw Error('This run has already been submitted.');const r=await api('/api/submit',{token:session.token,name:form.elements.name.value,superskill:form.elements.superskill.value,score:game.score(),run});run.submitted=true;status.textContent=`Published · ${r.score.toLocaleString()} verified points. Welcome to the board.`;button.textContent='Score published ✓';page=0;load();}
  catch(error){status.textContent=error.message;button.disabled=false;}
 });load();
}
