import * as THREE from 'three';
import './v10.css';
import './v11.css';
import './v12.css';
import './v13.css';
import './v14.css';
import './v15.css';
import './v17.css';
import './v18.css';
import './v19.css';
import './v20.css';
import './v24.css';
import { stepRealtime } from './sim/realtime.js';
import {RenderCadence} from './render/cadence.js';
import {disposeClonedMaterials} from './render/dispose.js';
import {applyStormLight} from './render/storm-look.js';
import { Campaign } from './sim/campaign.js';
import { ORGS } from './sim/orgs.js';
import { BUILTIN_DAYS, scenarioModel, daySeed } from './sim/scenarios.js';
import { TOWERS } from './sim/catalog.js';
import { key } from './sim/grid.js';
import { SceneRig } from './render/scene.js';
import { THEMES } from './render/themes.js';
import { Campus, loadCampusModels } from './render/campus.js';
import { AttackerLayer } from './render/creatures-v2.js';
import { RadarLabels } from './render/radar-labels.js';
import { ThreatMarkers } from './render/threat-markers.js';
import { ExposureMarkers } from './render/exposure-markers.js';
import './exposure.css';
import { Effects } from './render/effects.js';
import { buildTower, buildWall, updateTowerView, connectWalls, applyTowerTheme } from './render/controls-v2.js';
import { Soundtrack } from './audio/soundtrack.js';
import { CommandUI } from './ui/command.js';
import { recordRun } from './sim/replay.js';
import { beginRankedRun } from './ui/leaderboard.js';

document.body.innerHTML='<canvas id="c" aria-label="Interactive 3D security campus"></canvas><div id="interface"></div><div id="overlay"><div class="loading"><i class="live-dot"></i> ASSEMBLING THE COMMAND FLOOR…</div></div><div id="toast" role="status"></div>';
class App {
 constructor(){this.day=BUILTIN_DAYS[0];this.model=scenarioModel(this.day);this.speed=1;this.paused=false;this.running=false;this.labels=true;this.quality='high';this.selected=null;this.buildType=null;this.towerViews=new Map();this.wallViews=new Map();this.seenMessages=new Set();this.keys=new Set();this.audio=new Soundtrack();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.hit=new THREE.Vector3();this.frames=[];this.fps=0;this.renderCadence=new RenderCadence();this.simAccumulator=0;}
 async init(){this.rig=new SceneRig(document.querySelector('#c'));this.rig.applyTheme(THEMES.night);this.rig.ao.enabled=false;this.rig.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.rig.renderer.toneMappingExposure=1.15;this.rig.hemi.intensity=.95;this.rig.key.intensity=3.0;this.rig.rim.intensity=.55;this.rig.scene.environmentIntensity=.35;this.rig.scene.fog.density=.008;this.rig.bloom.strength=.24;this.rig.vignette.uniforms.darkness.value=1.0;this.rig.resize();this.rig.updateCamera();applyTowerTheme(THEMES.night);
 await this.rig.loadCampusEnvironment();applyStormLight(this.rig);
 this.campus=new Campus(this.rig,await loadCampusModels());this.attackers=new AttackerLayer(this.rig.scene,this.campus.models);this.effects=new Effects(this.rig.scene,this.rig.camera);this.radarLabels=new RadarLabels(this.rig.scene);this.threatMarkers=new ThreatMarkers(this.rig.scene);this.exposureMarkers=new ExposureMarkers(this.rig.scene);this.ui=new CommandUI(this);this.game=this.newGame('midcap','full');this.campus.rebuild(this.game);this.effects.views=this.campus.assetViews;this.input();this.backgroundTimer=setInterval(()=>{if(document.hidden){stepRealtime(this,performance.now());this.game.effects.length=0;this.game.popups.length=0;}},250);this.ui.update();this.ui.startScreen();this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
 newGame(org,mode){const game=new Campaign({model:this.model,org:ORGS[org],seed:daySeed(this.day.day),difficulty:1,mode});this.journal=recordRun(game);this.journal.eligible=this.day===BUILTIN_DAYS[0]&&mode==='full';return game;}
 start(org,mode){this.effects.clear();this.threatMarkers.clear();this.exposureMarkers.clear();this.game=this.newGame(org,mode);this.runTicket=this.journal.eligible?beginRankedRun(org):Promise.resolve({error:"Imported reports are practice-only."});this.running=true;this.paused=false;this.simAccumulator=0;this.simNow=performance.now();this.buildType=null;this.selected=null;this.ui.ended=false;this.ui.activityVisible=true;this.ui.opsHistory=false;this.ui.opsView='all';this.ui.opsExpanded=new Set();this.ui.workVisible=false;this.ui.workMode='team';this.ui.decisionExpanded=true;this.ui.decisionId=null;this.ui.tab='build';this.ui.track='Actions';this.ui.lastTrust=null;this.ui.callQueue=[];this.ui.closeCall();this.seenMessages.clear();this.audio.reset();this.audio.arm();this.campus.rebuild(this.game);this.effects.views=this.campus.assetViews;this.clearControls();this.ui.closeModal();this.ui.signature='';this.ui.inspectSignature='';this.ui.update();this.rig.goTo('command');this.ui.promotion();}
 async loadDay(day){const model=scenarioModel(day);this.day=day;this.model=model;}
 select(selected,focus=false){if(selected&&this.game.pendingDilemma)this.ui.decisionExpanded=false;this.selected=selected;this.buildType=null;this.campus.hideRange();this.ui.inspectSignature='';this.ui.renderInspect();if(focus&&selected?.kind==='asset'){const a=this.game.asset(selected.id);this.rig.goTo({x:a.x+2,z:a.y+.5,dist:26,pitch:.82});}}
 setQuality(q){this.quality=q;this.rig.renderer.setPixelRatio(q==='high'?Math.min(devicePixelRatio,1.5):1);this.campus.reflector.visible=q==='high';this.rig.bloom.enabled=q==='high';this.rig.smaa.enabled=q==='high';this.rig.resize();}
 point(e){const rect=this.rig.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.pointer,this.rig.camera);return this.ray.ray.intersectPlane(this.ground,this.hit)?.clone();}
 input(){const canvas=this.rig.renderer.domElement;
 canvas.addEventListener('pointerdown',e=>{if(this.modalOpen)return;this.drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,button:e.button};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(this.modalOpen)return;const p=this.point(e);if(this.drag){const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.x=e.clientX;this.drag.y=e.clientY;if(Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY)>5){this.drag.moved=true;if(this.drag.button===2||e.altKey)this.rig.rotate(-dx*.005,dy*.004);else this.rig.pan(-dx*this.rig.dist*.0015,dy*this.rig.dist*.0015);}}else if(this.buildType&&p){const x=Math.round(p.x),y=Math.round(p.z),valid=this.game.canPlace(this.buildType,x,y);this.campus.hover.visible=true;this.campus.hover.position.set(x,.025,y);this.campus.hover.material.color.set(valid.ok?0x88cba1:0xff3b30);const range=TOWERS[this.buildType].levels[0].range;if(range)this.campus.showRange(x,y,range);}});
 canvas.addEventListener('pointerup',e=>{const drag=this.drag;this.drag=null;if(!drag||drag.moved||this.modalOpen)return;if(e.button===2){this.buildType=null;this.campus.hover.visible=false;this.campus.hideRange();this.select(null);return;}if(e.button!==0)return;const p=this.point(e);if(!p)return;const x=Math.round(p.x),y=Math.round(p.z);if(this.buildType){const r=this.game.place(this.buildType,x,y);this.ui.toast(r.ok?'Control deployed.':r.reason,!r.ok);if(r.ok)this.audio.effect('build');return;}
 const meshes=[...this.campus.assetViews.values()].filter(v=>v.asset.discovered).map(v=>v.shape);const hits=this.ray.intersectObjects(meshes,true);if(hits.length){let ob=hits[0].object;while(ob&&!ob.parent?.asset)ob=ob.parent;const view=[...this.campus.assetViews.values()].find(v=>{let o=hits[0].object;while(o){if(o===v.group)return true;o=o.parent;}return false;});if(view){this.select({kind:'asset',id:view.asset.id});return;}}
 const at=this.attackers.pick(this.game,p.x,p.z);if(at){this.select({kind:'attacker',id:at.id});return;}const asset=[...this.game.assets.values()].find(a=>a.discovered&&x>=a.x&&x<a.x+2&&y>=a.y&&y<a.y+2);if(asset){this.select({kind:'asset',id:asset.id});return;}const tower=this.game.towers.find(t=>Math.hypot(t.x-p.x,t.y-p.z)<.8);if(tower){this.select({kind:'tower',id:tower.id});return;}const wall=this.game.walls.get(key(x,y));this.select(wall?{kind:'wall',x,y}:null);});
 canvas.addEventListener('pointercancel',()=>this.drag=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(this.modalOpen)return;e.preventDefault();this.rig.zoom(Math.exp(e.deltaY*.001),this.point(e));},{passive:false});
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){this.buildType=null;this.campus.hover.visible=false;this.campus.hideRange();this.select(null);if(this.modalOpen&&!this.game.pendingDilemma&&this.running)this.ui.closeModal();return;}if(this.modalOpen)return;this.keys.add(e.key.toLowerCase());if(e.code==='Space'){e.preventDefault();if(!e.repeat)this.paused=!this.paused;}const tower=Object.values(TOWERS).find(t=>t.hotkey===e.key);if(tower){this.buildType=tower.id;this.ui.tab='build';this.ui.signature='';}});
 window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{this.keys.clear();});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.paused=true;this.ui.toast('Graphics context lost. Reload the page to restart.',true);});}
 clearControls(){for(const v of this.towerViews.values()){this.rig.scene.remove(v.group);disposeClonedMaterials(v.group);}for(const v of this.wallViews.values()){this.rig.scene.remove(v);disposeClonedMaterials(v);}this.towerViews.clear();this.wallViews.clear();}
 syncControls(t){for(const tower of this.game.towers){let view=this.towerViews.get(tower.id);if(!view){view=buildTower(tower);this.rig.scene.add(view.group);this.towerViews.set(tower.id,view);}updateTowerView(view,tower,t,this.game);}for(const [id,v]of this.towerViews)if(!this.game.towers.some(t=>t.id===id)){this.rig.scene.remove(v.group);disposeClonedMaterials(v.group);this.towerViews.delete(id);}let changed=false;for(const [k,w]of this.game.walls)if(!this.wallViews.has(k)){const v=buildWall(w.x,w.y);this.rig.scene.add(v);this.wallViews.set(k,v);changed=true;}for(const [k,v]of this.wallViews)if(!this.game.walls.has(k)){this.rig.scene.remove(v);disposeClonedMaterials(v);this.wallViews.delete(k);changed=true;}if(changed)connectWalls(this.game.walls,this.wallViews);}
 frame(now){requestAnimationFrame(t=>this.frame(t));stepRealtime(this,now);if(!this.renderCadence.shouldRender(now,document.hidden))return;const dt=Math.min(.1,(now-this.last)/1000);this.last=now;this.frames.push(dt);if(this.frames.length>120)this.frames.shift();this.fps=Math.round(this.frames.length/this.frames.reduce((s,x)=>s+x,0));if(!this.modalOpen){const rate=dt*8;if(this.keys.has('w'))this.rig.pan(0,rate);if(this.keys.has('s'))this.rig.pan(0,-rate);if(this.keys.has('a'))this.rig.pan(-rate,0);if(this.keys.has('d'))this.rig.pan(rate,0);if(this.keys.has('q'))this.rig.rotate(dt*.5,0);if(this.keys.has('e'))this.rig.rotate(-dt*.5,0);}
 for(const m of this.game.messages)if(!this.seenMessages.has(m.seq)){this.seenMessages.add(m.seq);if(this.running)this.ui.enqueue(m.id);}for(const effect of this.game.effects.splice(0)){this.effects.spawn(effect,this.game);if(effect.type==='compromise')this.audio.effect('breach');if(effect.type==='kill')this.audio.effect('block');if(effect.type==='shot')this.audio.effect(effect.control==='waf'?'waf_arc':'ips_shot',effect.x);if(effect.type==='trapped')this.audio.effect('emp_burst',effect.x);if(effect.type==='barrier-hit')this.audio.effect('shell_impact',effect.x);if(effect.type==='barrier-break')this.audio.effect('barrier_break',effect.x);if(effect.type==='encryption')this.audio.effect('encryption');if(effect.type==='waf-audio')this.audio.effect('waf_arc',effect.x);}this.game.popups?.splice(0);this.syncControls(now/1000);this.campus.update(now/1000,dt,this.game,this.selected,this.labels);if(!this.buildType){this.campus.hover.visible=false;if(this.selected?.kind!=='tower')this.campus.hideRange();}this.attackers.sync(this.game,now/1000,this.rig.camera.quaternion);this.exposureMarkers.update(this.game,this.rig.camera,this.campus.assetViews,this.selected,now/1000,this.labels);this.radarLabels.update(this.game,this.rig.camera,this.selected);this.threatMarkers.update(this.game,this.rig.camera,this.campus.assetViews,now/1000);this.effects.update(dt);this.rig.update(dt);this.rig.render();this.audio.update(this.game);if(now-(this.lastUI||0)>200){this.ui.update();this.lastUI=now;}}
}
const app=new App();window.__app=app;app.init().catch(error=>{console.error(error);document.querySelector('#overlay').textContent=`Unable to initialize the game: ${error.message}. Reload to retry.`;});
